/* eslint-disable import/prefer-default-export,linebreak-style */

// LOGIN ACTIONS
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';


// GISTS ACTIONS
export const LOAD_GISTS_PENDING = 'LOAD_GISTS_PENDING';
export const LOAD_GISTS_SUCCESS = 'LOAD_GISTS_SUCCESS';
export const LOAD_GISTS_FAILED = 'LOAD_GISTS_FAILED';


// GIST ACTION
export const LOAD_GIST_PENDING = 'LOAD_GIST_PENDING';
export const LOAD_GIST_SUCCESS = 'LOAD_GIST_SUCCESS';
export const LOAD_GIST_FAILED = 'LOAD_GIST_FAILED';

// GIST ACTIONS FOR EDITOR
export const SET_GIST_EDIT_MODE = 'SET_GIST_EDIT_MODE';
export const SET_GIST_ADD_MODE = 'SET_GIST_ADD_MODE';
export const CANCEL_GIST_EDIT_MODE = 'CANCEL_GIST_EDIT_MODE';

// GIST DELETE ACTIONS
export const DELETE_GIST_PENDING = 'DELETE_GIST_PENDING';
export const DELETE_GIST_SUCCESS = 'DELETE_GIST_SUCCESS';
export const DELETE_GIST_FAILED = 'DELETE_GIST_FAILED';

// GIST EDIT ACIONS
export const EDIT_GIST_PENDING = 'EDIT_GIST_PENDING';
export const EDIT_GIST_SUCCESS = 'EDIT_GIST_SUCCESS';
export const EDIT_GIST_FAILED = 'EDIT_GIST_FAILED';

// GIST ADD ACTIONS
export const ADD_GIST_PENDING = 'ADD_GIST_PENDING';
export const ADD_GIST_SUCCESS = 'ADD_GIST_SUCCESS';
export const ADD_GIST_FAILED = 'ADD_GIST_FAILED';
