/* eslint-disable import/prefer-default-export,linebreak-style */

// LOGIN ACTIONS
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';


// GISTS ACTIONS
export const LOAD_GISTS_PENDING = 'LOAD_GISTS_PENDING';
export const LOAD_GISTS_SUCCESS = 'LOAD_GISTS_SUCCESS';
export const LOAD_GISTS_FAILED = 'LOAD_GISTS_FAILED';



// GIST ACTION
export const LOAD_GIST_PENDING = 'LOAD_GIST_PENDING';
export const LOAD_GIST_SUCCESS = 'LOAD_GIST_SUCCESS';
export const LOAD_GIST_FAILED = 'LOAD_GIST_FAILED';
